# Generated by Django 3.1 on 2020-08-10 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('dni', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido_paterno', models.CharField(max_length=20)),
                ('apellido_materno', models.CharField(max_length=20)),
                ('celular', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('codigo_usuario', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('dni_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmaciaApp.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('codigo_trabajador', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('cargo', models.CharField(max_length=20)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=6)),
                ('horario_entrada', models.TimeField()),
                ('horario_salida', models.TimeField()),
                ('dni_trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmaciaApp.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('codigo_doctor', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('especialidad', models.CharField(max_length=20)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=6)),
                ('horario_entrada', models.TimeField()),
                ('horario_salida', models.TimeField()),
                ('dni_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmaciaApp.persona')),
            ],
        ),
    ]
