# Generated by Django 3.1 on 2020-08-10 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmaciaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_medicamento', models.CharField(max_length=8)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stock', models.IntegerField()),
                ('indicaciones', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sala_virtual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_sala', models.CharField(max_length=8)),
                ('especialidad', models.CharField(max_length=20)),
                ('horario_inicio', models.TimeField()),
                ('horario_final', models.TimeField()),
                ('link_meet', models.CharField(max_length=50)),
                ('codigo_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmaciaApp.doctor')),
                ('codigo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmaciaApp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_receta', models.CharField(max_length=8)),
                ('observaciones', models.CharField(max_length=20)),
                ('codigo_sala', models.CharField(max_length=8)),
                ('codigo_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmaciaApp.doctor')),
                ('codigo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmaciaApp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Linea_receta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_linea', models.CharField(max_length=4)),
                ('cantidad', models.IntegerField()),
                ('indicaciones', models.CharField(max_length=50)),
                ('codigo_medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmaciaApp.medicamento')),
                ('codigo_receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmaciaApp.receta')),
            ],
        ),
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_historia', models.CharField(max_length=8)),
                ('codigo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmaciaApp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cita', models.CharField(max_length=8)),
                ('fecha', models.TimeField()),
                ('codigo_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmaciaApp.doctor')),
                ('codigo_historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmaciaApp.historia')),
            ],
        ),
    ]
